# Generated by Django 3.2.15 on 2022-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact', models.PositiveBigIntegerField(blank=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('F', 'Female'), ('O', 'Other')], default='m', max_length=6)),
                ('dob', models.DateField()),
                ('nation', models.CharField(choices=[('INDIA', 'INDIA'), ('ENGLAND', 'ENGLAND'), ('NEW ZEALAND', 'NEW ZEALAND'), ('WEST INDIES', 'WEST INDIES'), ('SOUTH AFRICA', 'SOUTH AFRICA'), ('SRI LANKA', 'SRI LANKA'), ('BANGLADESH', 'BANGLADESH'), ('AUSTRALIA', 'AUSTRALIA')], default='INDIA', max_length=12)),
            ],
        ),
    ]
