# Generated by Django 3.2.15 on 2022-08-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345678', max_length=16),
        ),
    ]
